services:
  carapi:
    image: ${DOCKER_REGISTRY-}carapi
    build:
      context: .
      dockerfile: CarApi/Dockerfile
    environment:
      Postgress__DbName: CarDb
      Postgress__DbUser: postgres
      Postgress__DbPassword: postgress
      Postgress__DbAddress: db
    depends_on:
      - db
    ports:
      - 5001:8080
  db:
   image: postgres
   restart: always
   volumes:
    -  CarApiDb:/var/lib/postgresql
   environment:
     POSTGRES_PASSWORD: postgress

volumes:
  CarApiDb: