services:
  carapi:
    image: ${DOCKER_REGISTRY-}carapi
    build:
      context: .
      dockerfile: CarApi/Dockerfile
    env_file: appsettings.env
    ports:
      - 5001:8080
  db:
   image: postgres
   restart: always
   volumes:
    -  CarApiDb:/var/lib/postgresql
   environment:
     POSTGRES_PASSWORD: postgress

volumes:
  CarApiDb: