- name: Update Car-Api Server
  hosts: Car-Api
  gather_facts: true
  tasks:

    - name: Perform compose pull
      ansible.builtin.command:
        chdir: ./Car-Api
        cmd: podman-compose pull
      become: true

    - name: Stop Compose
      ansible.builtin.command:
        chdir: ./Car-Api
        cmd: podman-compose down
      become: true

    - name: Start Compose
      ansible.builtin.command:
        chdir: ./Car-Api
        cmd: podman-compose up -d
      become: true