- name: Update Car-Api Server
  hosts: Car-Api
  gather_facts: true
  tasks:

- name: Perform compose pull
  ansible.builtin.command:
        chdir: ./Car-Api
        cmd: podman-compose pull
      register: pull_result
      become: true

- name: Stop Compose
  when: pull_result.stdout is search("Copying blob")
  ansible.builtin.command:
        chdir: ./Car-Api
        cmd: podman-compose down
      become: true

- name: Start Compose
  when: pull_result.stdout is search("Copying blob")
  ansible.builtin.command:
      chdir: ./Car-Api
      cmd: podman-compose down -d
      become: true