@CarApi_HostAddress = http://localhost:5158

GET {{CarApi_HostAddress}}/api/cars

###

@CarId=1
GET {{CarApi_HostAddress}}/api/cars/{{CarId}}

###

POST {{CarApi_HostAddress}}/api/cars
Content-Type: application/json

{
  "CarName":"A Car",
  "ModelId": 1,
  "OwnerId": 0,
  "OwnerFirstName":"Jane",
  "OwnerLastName":"Doe"
}

###

POST {{CarApi_HostAddress}}/api/cars
Content-Type: application/json

{
  "CarName":"Two Car",
  "ModelId": 1,
  "OwnerId": 2
}

###


PUT {{CarApi_HostAddress}}/api/cars/{{CarId}}
Content-Type: application/json

{
  "CarName":"Edited Car"
}

###

DELETE {{CarApi_HostAddress}}/api/cars/{{CarId}}

###

GET {{CarApi_HostAddress}}/api/people

###

@PersonId=7
GET {{CarApi_HostAddress}}/api/people/{{PersonId}}

###

POST {{CarApi_HostAddress}}/api/people
Content-Type: application/json

{
  "FirstName":"Jane",
  "LastName":"Doe"
}

###

PUT {{CarApi_HostAddress}}/api/people/{{PersonId}}
Content-Type: application/json

{
  "FirstName":"John",
  "LastName":"Doe"
}

###

DELETE {{CarApi_HostAddress}}/api/people?PersonId={{PersonId}}

###

GET {{CarApi_HostAddress}}/api/carmodels

###
